apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-deployment
  labels:
    app: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace
  template:
    metadata:
      labels:
        app: marketplace
    spec:
      containers:
      - name: marketplace
        image: fxnaranjom/claromarketplace:1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "150Mi"
            cpu: "150m"
 
---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  labels:
    app: marketplace 
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    app: marketplace